### ISSUE TITLE
angular 10 not working with angular/http

### ISSUE THREAD

**Issue by avimoraly** [bohoffi/ngx-airtable#20] opened 2020-08-27 16:29 UTC
**Describe the bug**
when starting my project i get this error: 
### ERROR in The target entry-point "ngx-airtable" has missing dependencies:
 - @angular/http

**To Reproduce**
start angular 9 with ngx-airtable 

**Expected behavior**

**Version information (please complete the following information):**
 - "version": "2.0.0"
 - Angular 10.0.14
 - Browser chrome

**Additional context**

**Comment by bohoffi** [comment] 2020-08-27 16:32
The issue is that the library isn't compatible with Angular 9+ yet.
I haven't had the time to upgrade it.

**Comment by tommueller** [comment] 2020-11-02 09:20
I just had a look at the code and it seems that the develop-branch is upgraded and should be working with Angular 9+?
Any specific issues that block releasing this?

**Comment by bohoffi** [comment] 2020-11-02 09:54
@tommueller the dev branch is close to 90% finished regarding a new release which contains a major API rebuilt. I'm aware for how long these compatibility issues are open now but I didn't had the time to cut the release...

**Comment by tommueller** [comment] 2020-11-02 09:56
Is it possible to support you in the rebuilt? Would love to use the library for a project starting this month, but we are running Angular 10 ...
I am happy to help out with some code here, but it's hard to tell what is unfinished ;)

**Comment by bohoffi** [comment] 2020-11-02 10:05
Some of the operators for former functions like `each-page` or `all` aren't finished (or even started) yet.

Another big portion is the `LinkedQuery` feature but I planned on moving this to a feature release which would introduce a breaking change for existing library users.

**Comment by bohoffi** [comment] 2020-11-02 11:22
Another approach I might try would be to create a new branch from the `2.0.0` tag, update the compatibility and release a `2.0.1`.

**Comment by bohoffi** [comment] 2020-11-02 13:10
@tommueller I gave the tag branching a quick shot and I was able to update the Angular dependencies.
What wasn't working was compiling the library out of the box.
I'll try to migrate that branch to an Angular workspace this later today which should get it running.

**Comment by tommueller** [comment] 2020-11-02 13:12
Cool, that sounds good! Thanks a lot for looking into this!

**Comment by bohoffi** [comment] 2020-11-02 16:49
@tommueller @avimoraly I've published version `ngx-airtable@2.0.1-next.0` as a Pre-release version.

**Comment by tommueller** [comment] 2020-11-03 08:40
@bohoffi just tested this and works like a charm! thanks so much!

**Comment by bohoffi** [comment] 2020-11-03 08:43
@tommueller I'm glad to hear that :)

I'll release a full `2.0.1` after some code cleanup

**Closed as completed by bohoffi** 2020-11-03 08:43 UTC
Labels: bug, dependencies
